# Load the .env file
ENV_FILE = .env

include $(ENV_FILE)
export $(shell sed 's/=.*//' .env)  # Export all variables

# Define variables
SSH_FOLDER_PATH ?= ~/.ssh
SSH_USER ?= ubuntu
SSH_KEY_NAME ?= ${APP_NAME}-key.pem
TERRAFORM_DIR = terraform
ANSIBLE_DIR = ansible
TFVARS_FILE = $(TERRAFORM_DIR)/terraform.tfvars



# Target to copy .env to terraform.tfvars
.PHONY: copy-env
copy-env:
	@echo "📂 Checking for existing variables in $(TFVARS_FILE)..."
	@while IFS='=' read -r key value; do \
		key=$$(echo "$$key" | tr -d '[:space:]'); \
		if [ -n "$$key" ] && ! grep -qE "^[[:space:]]*$$key[[:space:]]*=" $(TFVARS_FILE) 2>/dev/null; then \
			echo "$$key not found. Appending..."; \
			echo "$$key=$$value" >> $(TFVARS_FILE); \
		else \
			echo "✅ $$key already exists. Skipping."; \
		fi \
	done < $(ENV_FILE)

	@terraform -chdir=./terraform fmt

# Target to run Terraform
.PHONY: terraform
terraform: copy-env
	@echo "🚀 Running Terraform..."
	@cd $(TERRAFORM_DIR) && terraform validate && \
	 terraform init && terraform plan && \
	 terraform apply -auto-approve

# Target to run Ansible
.PHONY: ansible
ansible:
	@echo "🔧 Running Ansible Playbook..."
	@cd $(ANSIBLE_DIR) && ansible-playbook playbook.yml \
	--tags jenkins --private-key="$(SSH_FOLDER_PATH)/$(SSH_KEY_NAME)" -u $(SSH_USER) \
	-e "git_branch=main" \
	-e "jenkinsfile_path=Jenkinsfile" \
	-e "dockerhub_username=$(DOCKER_USERNAME)" \
	-e "dockerhub_password=${DOCKER_PASSWORD}" \
	-e "jenkins_namespace=$(JENKINS_NAMESPACE:-jenkins)" \
	-e "container_port=$(CONTAINER_PORT)" \
	-e "node_port=$(NODE_PORT)" \
	-e "jenkins_ssh_port=$(JENKINS_SSH_PORT:-2222)" \
	-e "ssh_node_port=$(SSH_NODE_PORT:-30022)" \
	-e "agent_port=$(AGENT_PORT:-50000)" \
	-e "agent_node_port=$(AGENT_NODE_PORT:-30050)" \
	-e "github_username=$(GITHUB_USERNAME)" \
	-e "github_access_token=$(GITHUB_ACCESS_TOKEN)" \
	-e "github_repo_name=$(GITHUB_REPO_NAME)" \
	-e "github_ssh_key_name=$(GITHUB_SSH_KEY_FILE_NAME)" \
	-e "secret_name_volume_key=$(SECRET_NAME_VOLUME_KEY:-jenkins-ssh-key)" \
	-e "app_name=$(APP_NAME)" \
	-e "jenkins_admin_password=$(JENKINS_ADMIN_PASSWORD)" \
	-e "jenkins_admin_username=$(JENKINS_ADMIN_USERNAME)" \
	
# Target to run both Terraform & Ansible
.PHONY: deploy
deploy: terraform ansible
	@echo "✅ Deployment complete!"

