---
# Playbook to setup the application infrastructure
# This playbook will setup the application infrastructure on AWS EC2 instances
- name: Configure Jenkins Host
  hosts: jenkins
  pre_tasks:
    - name: Print Jenkins URL
      ansible.builtin.debug:
        msg: "jenkins url: {{ jenkins_url }}"
      tags:
        - jenkins
        - kubernetes

  roles:
    - role: k8s
      tags: [jenkins, kubernetes, setup]
    - role: jenkins_user
      tags: [jenkins, secrets, setup]
    - role: jenkins_k8s
      tags: [jenkins, kubernetes, secrets]
    - role: jenkins_java
      tags: [jenkins, java]
    - role: jenkins_pipeline
      tags: [jenkins, pipeline]

- name: Configure Application Server
  hosts: servers
  roles:
    - role: docker
      tags: [docker, setup]
    - role: webapp
      tags: [webapp, application]
    - role: nginx
      tags: [nginx, webapp]


- name: Deploy  applications using jenkins pipeline deploy
  hosts: servers
  become: true
  roles:
    - role: jenkins_ansible_deploy
      tags: [jenkins_deploy, application]
      vars:
        jenkins_ansible_deploy_deploy_component: all
